name: My Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4.2.2
        
        - name: execute shell script
          run: |
            chmod +x Srikar720/Actions-1/.github/Script.sh
            ./Srikar720/Actions-1/.github/Script.sh
         

        #- name: listfiles
        #  run: ls
          
        #- name: Readfiles
        # run: cat README.md 