name: My Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4.2.2

        - name: Welcome Message
          run: |
            echo "My files"
            ls -ltra
            cat README.md

        - name: Install Cowsay
          run: sudo apt-get install cowsay -y

        - name: Generate ASCII Artwork 
          run: cowsay -f dog "Feed Me" >> Dog.txt

        - name: Test Files
          run: |
            ls -ltra
            cat dragon.txt

        #- name: listfiles
        #  run: ls
          
        #- name: Readfiles
        # run: cat README.md 